/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module blinker_10 (
    input clk,
    input rst,
    output reg blink,
    output reg [26:0] hold_time
  );
  
  
  
  reg [25:0] M_counter_d, M_counter_q = 1'h0;
  
  reg [26:0] M_holder_d, M_holder_q = 1'h0;
  
  always @* begin
    M_holder_d = M_holder_q;
    M_counter_d = M_counter_q;
    
    blink = M_counter_q[24+0-:1];
    M_counter_d = M_counter_q + 1'h1;
    hold_time = M_holder_q[0+26-:27];
    M_holder_d = M_holder_q + 1'h1;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_holder_q <= 1'h0;
    end else begin
      M_holder_q <= M_holder_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
