/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_5 (
    input [7:0] a,
    input [7:0] b,
    input [3:0] alufn,
    output reg [7:0] out
  );
  
  
  
  always @* begin
    
    case (alufn)
      4'h8: begin
        out = a & b;
      end
      4'he: begin
        out = a | b;
      end
      4'h6: begin
        out = a ^ b;
      end
      4'ha: begin
        out = a;
      end
      default: begin
        out = 1'h0;
      end
    endcase
  end
endmodule
