/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparator_7 (
    input [7:0] a,
    input [7:0] b,
    input [2:0] alufn,
    output reg [7:0] out
  );
  
  
  
  reg z;
  
  reg n;
  
  reg v;
  
  wire [8-1:0] M_adddd_out;
  wire [1-1:0] M_adddd_z;
  wire [1-1:0] M_adddd_v;
  wire [1-1:0] M_adddd_n;
  adder_6 adddd (
    .alufn(alufn[0+0-:1]),
    .a(a[0+7-:8]),
    .b(b[0+7-:8]),
    .out(M_adddd_out),
    .z(M_adddd_z),
    .v(M_adddd_v),
    .n(M_adddd_n)
  );
  
  always @* begin
    z = M_adddd_z;
    n = M_adddd_n;
    v = M_adddd_v;
    out = 1'h0;
    
    case (alufn[1+1-:2])
      2'h1: begin
        out[0+0-:1] = z;
      end
      2'h2: begin
        out[0+0-:1] = n ^ v;
      end
      2'h3: begin
        out[0+0-:1] = z | (n ^ v);
      end
      default: begin
        out[0+0-:1] = 1'h0;
      end
    endcase
  end
endmodule
