/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mod_10 (
    input [7:0] a,
    input [7:0] b,
    input [2:0] alufn,
    output reg [7:0] out
  );
  
  
  
  always @* begin
    if (a < b) begin
      out = a;
    end else begin
      out = a - (a / b) * b;
    end
  end
endmodule
